language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6

os:
  - linux
  - osx

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get github.com/DonnchaC/oniongateway/entry_proxy
  - >
      go test -v
      github.com/DonnchaC/oniongateway/entry_proxy
      -covermode=count
      -coverprofile=coverage.out
  - >
      while !
      $GOPATH/bin/goveralls
      -coverprofile=coverage.out
      -service=travis-ci
      -repotoken=$COVERALLS_TOKEN
      ; do sleep $(shuf -i 1-10 -n 1); done
